site_name: KubeCon NA 2022 Tutorial - K8s Setup Tools
nav:
  - Home: index.md
  - Kubectl: kubectl.md
  - Local Clusters:
    - Colima: local_cluster/colima.md
    - Podman: local_cluster/podman.md
    - Kind: local_cluster/kind.md
    - MiniKube: local_cluster/minikube.md
    - K3s: local_cluster/k3s.md
  - Shell Setup: shell_setup.md
  - Kubectl Tooling:
    - Kubectl: kubectl_tooling/kubectl.md
    - Krew: kubectl_tooling/krew.md
    - Kubecolor: kubectl_tooling/kubecolor.md
    - Stern: kubectl_tooling/stern.md
  - Kubernetes Interface:
    - K9s: interfaces/k9s.md
    - Lens: interfaces/lens.md
  - Development tooling: dev_tooling.md
  - Cleanup: cleanup/cleanup.md
  - Mkdocs help and examples: mkdocs.md
theme:
  features:
  #   - navigation.tabs
    - content.tabs.link
  favicon: images/kubecon_logo.jpeg
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
  logo: 'images/kubecon_logo.jpeg'
extra_css:
    - css/extra.css
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cloudnativeca
markdown_extensions:
  - admonition
  - pymdownx.details
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      # slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
      alternate_style: true 
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true