site_name: Gemini Code Assist Workshop 2 - Gemini CLI
nav:
  - Home: index.md
  - Installation: 0_install_cli.md
  - Gemini CLI - Vibecoding: 2_cli_vibecoding.md
  - Gemini CLI - Command Parameters: 1_cli_params.md
  - Gemini CLI - Configuration via settings.json: 3_cli_config.md 
#  - Gemini CLI - In-built Tools: 4_cli_build_in.md
  - Gemini CLI - MCP Servers: 5_cli_mcp.md
  - Gemini CLI - Custom slash commands: 6_cli_custom_commands.md
  - (EXTRA) Gemini CLI - Coding styles with Gemini.md: 7_cli_coding_style.md
  - Appendix A. MCP server for BQ: 8_cli_mcp_bq.md
theme:
  features:
  #   - navigation.tabs
    - content.tabs.link
    - content.code.copy
  favicon: images/gemini.jpeg
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
  logo: 'images/gemini_logo.jpeg'
extra_css:
    - css/extra.css
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cloudnativeca
markdown_extensions:
  - admonition
  - pymdownx.details
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      # slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
      alternate_style: true 
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
