site_name: KubeCon NA 2022 Tutorial - K8s Setup Tools
nav:
  - Home: index.md
  - Kubectl: kubectl.md
  - Local Clusters:
    - Podman: local_cluster/podman.md
    - Kind: local_cluster/kind.md
    - Other Options:
      - Rancher Desktop: local_cluster/options/rancher.md
      - Colima: local_cluster/options/colima.md
      - MiniKube: local_cluster/options/minikube.md
  - Deploying applications with kubectl: app_deployment.md
  - Shell Setup: shell_setup.md
  - Mkdocs help and examples: mkdocs.md
theme:
  features:
  #   - navigation.tabs
    - content.tabs.link
  favicon: images/kubecon_logo.jpeg
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
  logo: 'images/kubecon_logo.jpeg'
extra_css:
    - css/extra.css
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cloudnativeca
markdown_extensions:
  - admonition
  - pymdownx.details
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      # slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
      alternate_style: true 
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
