site_name: K8s Setup Tools
nav:
  - Home: index.md
theme:
  # features:
  #   - navigation.tabs
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
  logo: 'images/kubecon_logo.jpeg'
extra_css:
    - css/extra.css
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cloudnativeca
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes