apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: gowebapp

resources:
- app-deployment.yaml
- app-service.yaml
- mysql-deployment.yaml
- mysql-service.yaml
- mysql-secret.yaml