apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowebapp
  labels:
    run: gowebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gowebapp
  template:
    metadata:
      labels:
        run: gowebapp
    spec:
      containers:
      - env:
        - name: DB_PASSWORD
          value: rootpasswd
        image: ghcr.io/cloud-native-canada/k8s_setup_tools:app
        name: gowebapp
        ports:
          - containerPort: 9000
        livenessProbe:
          httpGet:
            path: /register
            port: 9000
          initialDelaySeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet: 
            path: /register
            port: 9000
          initialDelaySeconds: 25
          timeoutSeconds: 5
        resources:
          requests:
            cpu: "20m"
            memory: "10Mi"
          limits: 
            cpu: "50m"
            memory: "100Mi"